exclude: "^$"
fail_fast: false
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: safety check
        language: system
        always_run: true
        exclude: ".*"
      - id: npm-audit
        name: npm-audit
        language: system
        entry: npm audit --audit-level=critical
        always_run: true
        exclude: ".*"
